query allApps {
  applications {
    edges {
      node {
        id
        name
        parts {
          id
          name
          components {
            definition {
              id
              name
            }
          }
        }
      }
    }
  }
}
