mutation updatePart($input: UpdateApplicationPartInput!) {
  ApplicationPart_Update(input: $input) {
    application {
      id
      name
      parts {
        id
        name
        components {
          id
          name
        }
      }  
    }
  }
}
