#import "./Component.graphql"
mutation createComponent($input: CreateComponentInput!) {
  createComponent(input: $input) {
    component {
      ...Component
    }
    errors {
      ... on IUserError {
        message
      }
    }
  }
}
