mutation updateComponentSchema($input: UpdateComponentSchemaInput!) {
  updateComponentSchema(input: $input) {
    component {
      id
      name
      state
      schemaAsJson
      valuesAsJson      
    }
  }
}