query variableById($id: Uuid!) {
  variable(id: $id) {
    id
    name
    namespace
    isSecret
    values {
      id
      key {
        applicationId
        partId
        environmentId
      }
      value
      encryption {
        algorithm
      }
      application {
        id
        name
      }
      variable {
        name
        isSecret
      }
    }
  }
}
