mutation saveVariableValue($input: SaveVariableValueInput!) {
  Variable_SaveValue(input: $input) {
    value {
      id
      variableId
      applicationId
      partId
      environmentId
      encryption{
        keyProvider
        algorithm
      }
      value
    }
  }
}