mutation saveVariableValue($input: SaveVariableValueInput!) {
  Variable_SaveValue(input: $input) {
    value {
      id
      key {
        applicationId
        variableId
        partId
        environmentId
      }
      encryption{
        keyProvider
        algorithm
      }
      value
    }
  }
}